In [1]:
!python3 -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

# Numpy Datatype
### Numpy.nd.array

In [14]:
def show_array(arr):
    print('Array:', arr, sep='\n')
    print('Type:', type(arr))
    print('Shape:', arr.shape)
    print('Size:', arr.size)
    print('DType:', arr.dtype)
    print('Length:', len(arr))
    print('Dimension:', arr.ndim)

In [8]:
a = np.array([3,8,2,67,45])
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(len(a))

[ 3  8  2 67 45]
<class 'numpy.ndarray'>
(5,)
5
int64
5


In [15]:
# 10  11  13  14
# 45  22   9   2
# 6    5   1   8
b = np.array([[10,11,13,14], [45,22,9,2], [6,5,1,8]])
show_array(b)


Array:
[[10 11 13 14]
 [45 22  9  2]
 [ 6  5  1  8]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
Size: 12
DType: int64
Length: 3
Dimension: 2


In [16]:
                # 100  110  130  140
                # 145  122   19   12
                # 16    15   11   18
# 10  11  13  14
# 45  22   9   2
# 6    5   1   8
c = np.array([[[10,100],[11,110],[13,130],[14,140]], 
              [[45,145],[22,122],[9,19],[2,12]],
              [[6,16],[5,15],[1,11],[8,18]]])
show_array(c)

Array:
[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9  19]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4, 2)
Size: 24
DType: int64
Length: 3
Dimension: 3


In [ ]:
# Array Operations
### 1. Item Accessing: Subscripting, Slicing
### 2. Item Assignment
### 3. Item Insertion
### 4. Item Deletion
### 5. Arithmetic

In [17]:
b

array([[10, 11, 13, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [26]:
[[10,11,13,14], [45,22,9,2], [6,5,1,8]]
# b[0][0]
# b[1][1:]
# subscripting [1st, 2nd, 3rd , ....., nth dim]
# subscripting [1st:1st end: stepsize, 2nd, 3rd , ....., nth dim]
b[0,0]
b[1, -3:]
b[:, -2]
b[:, -2:-1]

array([[13],
       [ 9],
       [ 1]])

In [23]:
b[:, -2].shape

(3,)

In [27]:
# k = [3,5,7,3,7,89,3]
# k[2:3]
# k[2]

7

In [28]:
print(b[-1:,:])
print(c[:1, :2, :])
print(c[:, 1:2, :1])
print(c[-2:, -1:, :1])
print(c[:2, -2:, :])

[[6 5 1 8]]
[[[ 10 100]
  [ 11 110]]]
[[[11]]

 [[22]]

 [[ 5]]]
[[[2]]

 [[8]]]
[[[ 13 130]
  [ 14 140]]

 [[  9  19]
  [  2  12]]]


In [34]:
# Item Assignment
b[1,2] = 90
b

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [39]:
# Item Insertion
a = np.append(a, 80)
a

array([ 3,  8,  2, 67, 45, 80, 80])

In [43]:
np.append(b, [[9,90,900,9000]], axis = 0)  # axis = 0-> Row, 1->Col

array([[  10,   11,   13,   14],
       [  45,   22,   90,    2],
       [   6,    5,    1,    8],
       [   9,   90,  900, 9000]])

In [46]:
np.append(b, [[9],[90],[900]], axis = 1)

array([[ 10,  11,  13,  14,   9],
       [ 45,  22,  90,   2,  90],
       [  6,   5,   1,   8, 900]])

In [49]:
# Item Deletion
# del a[-1]  # This won't work
b1 = b.copy()

In [56]:
b1

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [55]:
np.delete(b1, 0, axis=0)

array([[45, 22, 90,  2],
       [ 6,  5,  1,  8]])

In [57]:
# Arithmetic Operations

In [61]:
b1 - 20

array([[-10,  -9,  -7,  -6],
       [ 25,   2,  70, -18],
       [-14, -15, -19, -12]])

In [62]:
b1 + 20

array([[ 30,  31,  33,  34],
       [ 65,  42, 110,  22],
       [ 26,  25,  21,  28]])

In [66]:
# Array Manipulation
#####################
# arr.reshape(....)
# arr.astype(...)

# More functions to create array
##################################
## np.array()
## np.arange()  -> array version of range func, also allows float
## np.linspace() -> start, end, no. of items
## np.ones() -> generate all values as '1'
## np.zeros() -> generate all values as '0'
## np.random.random()
## np.random.randint()

In [65]:
b1.reshape(2,6,1,1)

array([[[[10]],

        [[11]],

        [[13]],

        [[14]],

        [[45]],

        [[22]]],


       [[[90]],

        [[ 2]],

        [[ 6]],

        [[ 5]],

        [[ 1]],

        [[ 8]]]])

In [68]:
b.dtype

dtype('int64')

In [69]:
b.astype(float)

array([[10., 11., 13., 14.],
       [45., 22., 90.,  2.],
       [ 6.,  5.,  1.,  8.]])

In [70]:
b.astype('uint16')

array([[10, 11, 13, 14],
       [45, 22, 90,  2],
       [ 6,  5,  1,  8]], dtype=uint16)

In [73]:
np.ones((3,4), dtype='int') * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])