In [1]:
#artificial neural network
!ls

decisiontree.ipynb	matplotlib.ipynb    population.ipynb
hello.ipynb		poly_revised.ipynb  socket.ipynb
image-classifier.ipynb	poly_test.ipynb     tensorflow.ipynb


In [4]:
!lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7763 64-Core Processor
Stepping:                        1
CPU MHz:                         2445.426
BogoMIPS:                        4890.85
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        1 MiB
L3 cache:                        32 MiB
NUMA no

In [3]:
!ls -a

.		    image-classifier.ipynb  population.ipynb
..		    matplotlib.ipynb	    socket.ipynb
decisiontree.ipynb  poly_revised.ipynb	    tensorflow.ipynb
hello.ipynb	    poly_test.ipynb


In [6]:
#to check RAM
!free -m

              total        used        free      shared  buff/cache   available
Mem:          15991        1797        5654           4        8540       13854
Swap:             0           0           0


In [7]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay          31G   15G   14G  52% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
/dev/root        29G   21G  8.0G  73% /usr/sbin/docker-init
/dev/sda1       118G  216K  112G   1% /tmp
/dev/loop3       31G   15G   14G  52% /workspaces


In [11]:
!pip list |grep -i tensorflow

tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.33.0


In [12]:
!pip install tensorflow

In [2]:
#checking version
import tensorflow as tf
print(tf.__version__)

2023-09-04 07:16:58.175849: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-04 07:17:01.464792: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-04 07:17:01.465692: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-04 07:17:06.561371: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.13.0


In [8]:
x=tf.constant((1,2,3))
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [12]:
y=tf.ones((4,4),dtype='int32')
y1=tf.ones((3,3),dtype=tf.int64)
y2=tf.zeros((2,3))
y3=tf.eye(3)#identity matrix
tf.
print(y3)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [13]:
dir(tf)

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_API_MODULE',
 '_LazyLoader',
 '__all__',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__cxx_version__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__internal__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__operators__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_api',
 '_compat',
 '_current_file_location',
 '_current_module',
 '_distutils',
 '_estimator_module',
 '_fi',
 '_initializers',
 '_inspect',
 '_keras',
 '_keras_module',
 '_keras_package',
 '_kerne

In [27]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd 
import matplotlib.pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'#ignoring logs of tensorflow

In [28]:
import numpy as np
np.random.seed(0)
x=np.random.rand(100,2)
y=(x[:,0]+x[:,1]>1).astype(int)#binary classifier
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [29]:
#split by maths
ratio1=0.8
ratio1_index=int(len(x)*ratio1)
ratio1_index

80

In [30]:
train_x,test_x=x[:ratio1_index],x[ratio1_index:]
train_y,test_y=y[:ratio1_index],y[ratio1_index:]

In [31]:
#define sequential ANN using keras
keras.Sequential()

In [ ]:
#activation function
#cost function
#auto incremental of epoch(auto-calling)
